.Model SMALL
.STACK 100h
.data
.CODE

MAIN PROC
    
;DISPLAY PROMPT TO THE USER

MOV AH,2 ;DISPLAY CHARACTER FUNTION  

MOV DL,'?' ;CHARACTER IS '?'    dl prints single character    

INT 21H ;DISPLAY THE DL CHAR (?)

;INTPUT A CHARACTER       

MOV AH,1 ;READ CHARACTER FUNCTION 
     
INT 21H ;CHARACTER IS IN AL     

MOV BL,AL ; SAVE INPUT TO BL REG

;GO TO NEW LINE

MOV AH,2 ;DISPLAY CHARACTER FUNCTION 

MOV DL,0Dh ; CARRIAGE RETURN  

INT 21H          ;execute carriage return

MOV DL,0AH       ;line feed to display

INT 21H ;EXECUTE LINE FEED 

;DISPLAY CHARACTER  

MOV DL,BL ;RETRIEVE CHARACTER  

INT 21H

;RETURN TO DOS       

MOV AH,4ch ; TERMINATE THE CURRENT PROCESS AND TO CONTROL TO INVOKING PROCESS

INT 21H ;termination the execution of program return control to DOS

MAIN ENDP

END MAIN
